### PR TITLE
Redmine 3.4

### PR DESCRIPTION
**Pull request by fabricerobin**
Hi,

We want to share the adaptations we have to made to be able to use this plugin with Redmine 3.4

Regards

### CODE REVIEW

**Comment by myrandor** [comment]
How can I download there changes?

**Comment by fabricerobin** [comment]
Hi,

You can accept the pull request :-)
or if you want to test it before, you can get the full source on
https://github.com/Neticoa/redmine_workflow_hidden_fields

Regards,
Fabrice

**Comment by jouve** [comment]
Hi,

This seems to work great !

**Comment by alexwais** [comment]
thanks!

**Comment by fabricerobin** [comment]
De nada !

2018-03-26 11:14 GMT+02:00 Alex Wais <notifications@github.com>:

**Pull request merged**
